In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(16).reshape(4,4),
                   index=['台北','台中', '台南', '高雄'],
                   columns=['one', 'two', 'three', 'four'])
df

    one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [2]:
#drop
df.drop(index=['台北', '高雄'], inplace=True)
df

    one  two  three  four
台中    4    5      6     7
台南    8    9     10    11

In [ ]:
#排序和排名

scores = np.random.randint(50,101,size=(50, 5))
df = pd.DataFrame(scores,
                  columns=['國文', '英文', '數學', '自然', '社會'],
                  index=['學生' + str(i) for i in range(1, 51)])
df.index.name = '學生'
df.columns.name = '科目'
sum_values = df.sum(axis=1)
mean_values = df.mean(axis=1)
df['總分'] = sum_values
df['平均'] = mean_values
df

In [ ]:
#排序和排名
#rank()
rank_values = sum_values.rank(method='max')
df['排名'] = rank_values
df

In [8]:
#排序和排名
#rank()
rank_values = sum_values.rank(method='min', ascending=False)
df['排名'] = rank_values
df

科目    國文  英文  數學   自然   社會   總分    平均    排名
學生
學生1   93  74  50  100   77  394  78.8  15.0
學生2   85  77  88   71   88  409  81.8   7.0
學生3   85  76  70   58   93  382  76.4  20.0
學生4   90  77  65   91   95  418  83.6   3.0
學生5   71  93  50   68   61  343  68.6  43.0
學生6   94  90  71   99   56  410  82.0   6.0
學生7   58  97  57   73   98  383  76.6  19.0
學生8   54  79  76   78   70  357  71.4  34.0
學生9   85  77  91   54  100  407  81.4   9.0
學生10  92  93  67   68   57  377  75.4  24.0
學生11  75  61  68   72   81  357  71.4  34.0
學生12  52  77  83   77   95  384  76.8  18.0
學生13  97  59  86   69   90  401  80.2  12.0
學生14  60  63  95   80   77  375  75.0  26.0
學生15  58  52  87   77   83  357  71.4  34.0
學生16  59  58  92   79   69  357  71.4  34.0
學生17  56  71  80   95   74  376  75.2  25.0
學生18  53  71  57   70   57  308  61.6  50.0
學生19  91  88  68   78   80  405  81.0  11.0
學生20  59  82  92   54   86  373  74.6  27.0
學生21  53  59  73   73   95  353  70.6  39.0
學生22  81  51  99   53   58  342  68.4  44.0
學生23  70  73  72   60   94  369  73.8  31.0
學生24  81  85  86   53   95  400  80.0  13.0
學生25  57  53  77   85   93  365  73.0  32.0
學生26  76  51  52   94   99  372  74.4  28.0
學生27  87  72  74   97   76  406  81.2  10.0
學生28  75  59  64   54   93  345  69.0  41.0
學生29  79  72  84   94   83  412  82.4   5.0
學生30  62  68  65   65   67  327  65.4  48.0
學生31  90  78  73   87   52  380  76.0  21.0
學生32  51  84  92   75   94  396  79.2  14.0
學生33  80  75  74   60   98  387  77.4  17.0
學生34  60  56  83   51   74  324  64.8  49.0
學生35  80  57  78   65   91  371  74.2  30.0
學生36  70  99  56   63   60  348  69.6  40.0
學生37  97  77  71   93   95  433  86.6   1.0
學生38  76  60  92   56   72  356  71.2  38.0
學生39  50  97  74   65   73  359  71.8  33.0
學生40  92  70  67   91   93  413  82.6   4.0
學生41  60  75  83   81   80  379  75.8  22.0
學生42  55  91  90   87   96  419  83.8   2.0
學生43  70  50  56   88   73  337  67.4  47.0
學生44  94  78  78   56   72  378  75.6  23.0
學生45  50  95  59   80   55  339  67.8  46.0
學生46  93  85  76   58   96  408  81.6   8.0
學生47  82  98  74   79   57  390  78.0  16.0
學生48  59  74  71   84   84  372  74.4  28.0
學生49  59  75  61   72   74  341  68.2  45.0
學生50  62  63  56   68   95  344  68.8  42.0

In [9]:
#sort_values()
#sort_index()
df1 = df.sort_values(by='總分', ascending=False)
df1

科目    國文  英文  數學   自然   社會   總分    平均    排名
學生
學生37  97  77  71   93   95  433  86.6   1.0
學生42  55  91  90   87   96  419  83.8   2.0
學生4   90  77  65   91   95  418  83.6   3.0
學生40  92  70  67   91   93  413  82.6   4.0
學生29  79  72  84   94   83  412  82.4   5.0
學生6   94  90  71   99   56  410  82.0   6.0
學生2   85  77  88   71   88  409  81.8   7.0
學生46  93  85  76   58   96  408  81.6   8.0
學生9   85  77  91   54  100  407  81.4   9.0
學生27  87  72  74   97   76  406  81.2  10.0
學生19  91  88  68   78   80  405  81.0  11.0
學生13  97  59  86   69   90  401  80.2  12.0
學生24  81  85  86   53   95  400  80.0  13.0
學生32  51  84  92   75   94  396  79.2  14.0
學生1   93  74  50  100   77  394  78.8  15.0
學生47  82  98  74   79   57  390  78.0  16.0
學生33  80  75  74   60   98  387  77.4  17.0
學生12  52  77  83   77   95  384  76.8  18.0
學生7   58  97  57   73   98  383  76.6  19.0
學生3   85  76  70   58   93  382  76.4  20.0
學生31  90  78  73   87   52  380  76.0  21.0
學生41  60  75  83   81   80  379  75.8  22.0
學生44  94  78  78   56   72  378  75.6  23.0
學生10  92  93  67   68   57  377  75.4  24.0
學生17  56  71  80   95   74  376  75.2  25.0
學生14  60  63  95   80   77  375  75.0  26.0
學生20  59  82  92   54   86  373  74.6  27.0
學生26  76  51  52   94   99  372  74.4  28.0
學生48  59  74  71   84   84  372  74.4  28.0
學生35  80  57  78   65   91  371  74.2  30.0
學生23  70  73  72   60   94  369  73.8  31.0
學生25  57  53  77   85   93  365  73.0  32.0
學生39  50  97  74   65   73  359  71.8  33.0
學生11  75  61  68   72   81  357  71.4  34.0
學生8   54  79  76   78   70  357  71.4  34.0
學生16  59  58  92   79   69  357  71.4  34.0
學生15  58  52  87   77   83  357  71.4  34.0
學生38  76  60  92   56   72  356  71.2  38.0
學生21  53  59  73   73   95  353  70.6  39.0
學生36  70  99  56   63   60  348  69.6  40.0
學生28  75  59  64   54   93  345  69.0  41.0
學生50  62  63  56   68   95  344  68.8  42.0
學生5   71  93  50   68   61  343  68.6  43.0
學生22  81  51  99   53   58  342  68.4  44.0
學生49  59  75  61   72   74  341  68.2  45.0
學生45  50  95  59   80   55  339  67.8  46.0
學生43  70  50  56   88   73  337  67.4  47.0
學生30  62  68  65   65   67  327  65.4  48.0
學生34  60  56  83   51   74  324  64.8  49.0
學生18  53  71  57   70   57  308  61.6  50.0